### ISSUE TITLE
[FR] add beta switch for beta frimware

### ISSUE THREAD

**Issue by scns** [scns/myESPhome#124]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

add a switch in the device to switch firmware version from prod to beta

### Suggested solution

```YAML
switch:
  - platform: template
    id: beta_firmware
    name: Beta firmware
    icon: "mdi:test-tube"
    disabled_by_default: true
    entity_category: diagnostic
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "OTA updates set to use Beta firmware"
      - lambda: id(update_http_request).set_source_url("https://[URL TO MANIFEST/manifest-beta.json");
    on_turn_off:
      - logger.log: "OTA updates set to use Production firmware"
      - lambda: id(update_http_request).set_source_url("https://[URL TO MANIFEST]/manifest.json");
  ```

### Describe alternatives you've considered

...

### Do you want to develop this?

- [X] I want to develop this.
